name: Update UG1305

on:
  push:
    branches:
      - 2024.1_next
    paths:
      - 'docs/Getting_Started/Versal-EDT/**'

# Permissions to write to the repository are required
permissions: write-all

jobs:
  update_docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Emb-Design-Tutorials repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SSH folder and file
        run: |
          SSH_DIR="${HOME}/.ssh"
          mkdir -p "$SSH_DIR"
          touch "${SSH_DIR}/known_hosts"
          chmod 700 "$SSH_DIR"
          chmod 600 "${SSH_DIR}/known_hosts"
      - name: Set up SSH
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem
          rm -f private_key.pem
          ssh-keyscan gitenterprise.xilinx.com >> "$HOME/.ssh/known_hosts"
      - name: Checkout techdocs/UG1305 repository
        uses: actions/checkout@v2
        with:
          repository: techdocs/UG1305
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: UG1305_repo
          ref: main

      - name: Delete and replace 'docs' and 'ref_files' folder contents, and 'Versal-EDT.rst' in techdocs-UG1305
        run: |
          rm -rf UG1305_repo/build_html/source/docs/*
          rm -rf UG1305_repo/build_html/source/ref_files/*
          rm -f UG1305_repo/build_html/source/Versal-EDT.rst
          cp -r docs/Getting_Started/Versal-EDT/docs UG1305_repo/build_html/source/docs
          cp -r docs/Getting_Started/Versal-EDT/ref_files UG1305_repo/build_html/source/ref_files
          cp docs/Getting_Started/Versal-EDT/Versal-EDT.rst UG1305_repo/build_html/source/Versal-EDT.rst

      - name: Commit and push changes to techdocs-UG1305
        run: |
          cd UG1305_repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Update UG1305 documentation from Emb-Design-Tutorials repository"
          git push