# This YAML file defines a GitHub Actions workflow for updating the
# UG1209 documentation whenever changes are pushed to the '2024.2_next'
# branch of the Emb-Design-Tutorials repository affecting files under
# the 'docs/Performance/Performance_Benchmark/Dhrystone/' directory.

name: Update XD071 2024.2

# The 'on' section defines the events that trigger the workflow.
on:
  push:
    branches:
      - 2024.2_next
    paths:
      - 'docs/Performance/Performance_Benchmark/Dhrystone/**'

# Permissions to write to the repository are required.
permissions: write-all

# The 'jobs' section lists the jobs that compose the workflow.
jobs:
  update_docs:
    # This job runs on an Ubuntu 22.04 virtual environment.
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the Emb-Design-Tutorials repository with a full
      # Git history by setting fetch-depth to 0.
      - name: Checkout Emb-Design-Tutorials repository
        uses: actions/checkout@v2
        with:
          ref: '2024.2_next'  
          fetch-depth: 0

      # Step 2: Set up the SSH directory and known_hosts file.
      - name: Set up SSH folder and file
        run: |
          SSH_DIR="${HOME}/.ssh"
          mkdir -p "$SSH_DIR"
          touch "${SSH_DIR}/known_hosts"
          chmod 700 "$SSH_DIR"
          chmod 600 "${SSH_DIR}/known_hosts"
      
      # Step 3: Set up the SSH agent using the private deployment key
      # stored in the 'DEPLOY_KEY' secret.
      - name: Set up SSH
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem
          rm -f private_key.pem
          ssh-keyscan gitenterprise.xilinx.com >> "$HOME/.ssh/known_hosts"
      
      # Step 4: Check out the '2024.2_next' branch of the techdocs/XD071
      # repository with the SSH key stored in the 'xd071_deploy_key' secret,
      # placing its contents in the 'XD071_repo' directory.
      - name: Checkout techdocs/XD071 repository
        uses: actions/checkout@v2
        with:
          repository: techdocs/XD071
          ssh-key: ${{ secrets.xd071_deploy_key }}
          path: XD071_repo
          ref: 2024.2_next

      # Step 5: Copy the contents of the 'docs/Performance/Performance_Benchmark/Dhrystone/'
      # directory to the 'build_html/source/' directory of the XD071 repository.
      - name: Move contents of Performance_Benchmark/Dhrystone to xd071_repo
        run: |
          cp -r docs/Performance/Performance_Benchmark/Dhrystone/* XD071_repo/build_html/source/
      
      # Step 6: Commit the changes in the XD071 repository and push them.
      - name: Commit and push changes to techdocs-XD071
        run: |
          cd XD071_repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Update XD071 2024.2 documentation from Emb-Design-Tutorials repository"
          git push
