name: Update XD131 2024.2

on:
  push:
    branches:
      - 2024.2_next
    paths:
      - 'docs/Getting_Started/microblaze-system/**'

# Permissions to write to the repository are required
permissions: write-all

jobs:
  update_docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Emb-Design-Tutorials repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SSH folder and file
        run: |
          SSH_DIR="${HOME}/.ssh"
          mkdir -p "$SSH_DIR"
          touch "${SSH_DIR}/known_hosts"
          chmod 700 "$SSH_DIR"
          chmod 600 "${SSH_DIR}/known_hosts"
      - name: Set up SSH
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem
          rm -f private_key.pem
          ssh-keyscan gitenterprise.xilinx.com >> "$HOME/.ssh/known_hosts"
      - name: Checkout techdocs/XD131 repository
        uses: actions/checkout@v2
        with:
          repository: techdocs/XD131
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: XD131_repo
          ref: 2024.2_next

      - name: Delete and replace 'docs' folder contents, and 'index.rst' in techdocs-XD131
        run: |
          rm -rf XD131_repo/build_html/source/docs/*
          rm -f XD131_repo/build_html/source/index.rst
          cp -r docs/Getting_Started/microblaze-system/media XD131_repo/build_html/source/docs/media
          cp -r docs/Getting_Started/microblaze-system/tutorials XD131_repo/build_html/source/docs/tutorials
          cp docs/Getting_Started/microblaze-system/index.rst XD131_repo/build_html/source/index.rst

      - name: Commit and push changes to techdocs-XD131
        run: |
          cd XD131_repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Update XD131 2024.2 documentation from Emb-Design-Tutorials repository"
          git push